// The URL arrays of the relay chain node
export const RELAY_CHAIN_URLS: Record<string, string[]> = {
    kusama: [
        "wss://kusama.api.onfinality.io/public-ws",
        "wss://kusama-rpc.publicnode.com",
        "wss://kusama-rpc.dwellir.com",
        "wss://kusama-rpc-tn.dwellir.com",
        "wss://rpc-kusama.helixstreet.io",
        "wss://rpc.ibp.network/kusama",
        "wss://kusama.dotters.network",
        "wss://rpc-kusama.luckyfriday.io",
        "wss://kusama.public.curie.radiumblock.co/ws",
        "wss://ksm-rpc.stakeworld.io",
    ],
    polkadot: [
        "wss://polkadot.api.onfinality.io/public-ws",
        "wss://polkadot-rpc.publicnode.com",
        "wss://polkadot-public-rpc.blockops.network/ws",
        "wss://polkadot-rpc.dwellir.com",
        "wss://polkadot-rpc-tn.dwellir.com",
        "wss://rpc-polkadot.helixstreet.io",
        "wss://rpc.ibp.network/polkadot",
        "wss://polkadot.dotters.network",
        "wss://rpc-polkadot.luckyfriday.io",
        "wss://polkadot.rpc.permanence.io",
        "wss://polkadot.public.curie.radiumblock.co/ws",
        "wss://dot-rpc.stakeworld.io",
        "wss://polkadot.rpc.subquery.network/public/ws",
    ],
    westend: [
        "wss://westend-rpc.dwellir.com",
        "wss://westend-rpc-tn.dwellir.com",
        "wss://rpc.ibp.network/westend",
        "wss://westend.dotters.network",
        "wss://westend.api.onfinality.io/public-ws",
        "wss://westend-rpc.polkadot.io",
        "wss://westend.public.curie.radiumblock.co/ws",
    ],
    paseo: [
        "wss://paseo.rpc.amforc.com",
        "wss://paseo-rpc.dwellir.com",
        "wss://rpc.ibp.network/paseo",
        "wss://paseo.dotters.network",
        "wss://pas-rpc.stakeworld.io"
    ],
}